"""Split into PlayInfo and MediaInfo

Revision ID: f95cbdc5de3d
Revises: d3c4e42d95db
Create Date: 2021-05-29 06:04:13.598507

"""
import sys
from os.path import abspath, dirname
sys.path.append(dirname(dirname(dirname(abspath(__file__)))))

from alembic import op
import sqlalchemy as sa

from sqlalchemy import orm
from sqlalchemy import Column, String, Integer
from sqlalchemy.ext.declarative import declarative_base
from models.media_list import PlayInfo
from models.media_list import MediaInfo
from models.media_list import BaseInfo


Base = declarative_base()


# revision identifiers, used by Alembic.
revision = 'f95cbdc5de3d'
down_revision = 'd3c4e42d95db'
branch_labels = None
depends_on = None


class MediaListDB(Base):
    __table_args__ = {'mysql_engine': 'InnoDB'}
    __table_initialized__ = False
    __tablename__ = 'media_list'

    mysql_character_set = 'utf8'

    id = Column('id', Integer(), autoincrement=True, nullable=False, primary_key=True)
    name = Column(String(255), nullable=True)
    path = Column(String(255), nullable=False)
    priority = Column('priority', Integer(), nullable=False)
    played = Column('played', Integer(), nullable=False)
    failed = Column('failed', Integer(), nullable=False)
    jumped = Column('jumped', Integer(), nullable=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('base_info',
                        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                        sa.Column('path', sa.String(length=255), nullable=False),
                        sa.PrimaryKeyConstraint('id'),
                        mysql_engine='InnoDB'
                        )

        op.create_table('play_info',
                        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                        # sa.Column('name', sa.String(length=255), nullable=True),
                        sa.Column('priority', sa.Integer(), nullable=False),
                        sa.Column('played', sa.Integer(), nullable=False),
                        sa.Column('finished', sa.Integer(), nullable=False),
                        sa.Column('jumped', sa.Integer(), nullable=False),
                        sa.Column('media_id', sa.Integer(), nullable=False),
                        sa.PrimaryKeyConstraint('id'),
                        # sa.ForeignKeyConstraint('media_id', BaseInfo.id),
                        mysql_engine='InnoDB'
                        )

        op.create_table('media_info',
                        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                        sa.Column('simple_name', sa.String(length=255), nullable=True),
                        sa.Column('origin_name', sa.String(length=255), nullable=True),
                        sa.Column('year', sa.String(length=8), nullable=True),
                        sa.Column('media_id', sa.Integer(), nullable=True),
                        # sa.ForeignKeyConstraint(['media_id'], ['play_info.id'], ),
                        sa.PrimaryKeyConstraint('id'),
                        mysql_engine='InnoDB'
                        )

        bind = op.get_bind()

        session = orm.Session(bind=bind)

        # Should have other method setting table to utf8
        bind.execute(sa.sql.text('ALTER table base_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci'))
        bind.execute(sa.sql.text('ALTER table play_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci'))
        bind.execute(sa.sql.text('ALTER table media_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci'))

        with session.begin(subtransactions=True):
            raw_dbs = session.query(MediaListDB).all()

            for raw_db in raw_dbs:
                name = raw_db.name
                path = raw_db.path
                priority = raw_db.priority

                base = BaseInfo(path=path)
                base.play_info = PlayInfo(priority=priority, played=0, finished=0, jumped=0)
                base.media_info = MediaInfo(simple_name=name, origin_name='', year='')

                session.add(base)

    except Exception:
        try:
            op.drop_table('media_info')
        except Exception:
            pass

        try:
            op.drop_table('play_info')
        except Exception:
            pass

        try:
            op.drop_table('base_info')
        except Exception:
            pass

        raise

    # do not need media_list table now
    # op.drop_table('media_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    op.create_table('media_list',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('played', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('failed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('jumped', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    bind.execute(sa.sql.text('ALTER table media_list CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci'))
    """
    op.drop_table('media_info')
    op.drop_table('play_info')
    op.drop_table('base_info')
    # ### end Alembic commands ###
